export const PICK_INGREDIENT = "PICK_INGREDIENT";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const OPEN_DESCRIPTION = "OPEN_DESCRIPTION";
export const COMPLETE_ORDER = "COMPLETE_ORDER";
